### ISSUE TITLE
(Re)Start Game

### ISSUE THREAD

**Issue by holubond** [mazanec202/rust-uno#18]
[WIKI](https://github.com/mazanec202/rust-uno/wiki/HTTP-API#restart-game)

**Frontend**
- [x] Autor hry má v lobby možnost spustit hru
- [x] Autor má v přehledu skončené hry možnost restartovat hru
- [x] Spuštění hry zašle dotaz na server dle WIKI a vhodně interpretuje odpověď *(stačí pokrýt případy neúspěchu, v případě úspěchu totiž přijde WS zpráva, kterou vhodně interpretuješ - bude popsáno v dalším issue)*
- [x] Hezké error zprávy

**Util**
- [x] Existuje endpoint pro start/restart hry podle specifikace na WIKI
- [x] Ověří, že daná hra existuje
- [x] Ověří pomocí tokenu, že odesilatelem je skutečně autor hry
- [x] zavolá nad hrou příslušnou metodu pro start/restart *(implementuje domain člověk)*

**Domain**
- [x] Poskytne funkci, která hru spustí/restartuje
    - [x] Je nastavený hráč na tahu (náhodně vybrán)
    - [x] Pořadí tahů hráčů je náhodně nastaveno
    - [x] balíček je se všemi kartami zamíchán a každému hráči je rozdán počet karet podle pravidel (po vynulování případných předchozích karet hráčů)
    - [x] každému hráči je odeslána WS Status zpráva
    - [x] Případné výsledné pořadí hráčů je vynulováno
- [x] Pokud hra již běží, restart neprovádí a vrátí chybu

*Snad jsem pokryl všechny nutné kroky, feel free to add some*

**Comment by holubond** [comment]
Domain práce hotová, odstraňuju label

**Comment by AurumTheEnd** [comment]
A já odstraňuju sebe:
