### ISSUE TITLE
Draw cards

### ISSUE THREAD

**Issue by holubond** [mazanec202/rust-uno#30]
[WIKI REST](https://github.com/mazanec202/rust-uno/wiki/HTTP-API#draw-cards)
[WIKI WS](https://github.com/mazanec202/rust-uno/wiki/WS-API#draw)

Pro M1 navrhuju zasílat dotaz na server i v případě, že má daný hráč kartu, kterou může zahrát. V takovém případě přijde ze serveru chybová odpověď a hráč bude nucen provést jinou akci.

*Došlo k drobné změně oproti původní specifikaci - hráč na tahu je o výsledku notifikován přes REST (nejde mu WS Message), pouze ostatním jde WS Message*

**Frontend**
*Lízání karty hráčem (REST)*
- [x] Hráč na tahu si může líznout kartu (kliknutím na balíček, kliknutím na tlačítko, co uznáš za vhodné)
- [x] Pokud hráči přijde bezchybná odpověď, přidá si kartu do ruky (a změní hráče na tahu) **Potřeba zkontrolovat**

*Reakce na akci jiného hráče (reakce na WS DRAW Message)*
- [x] hráči, který si lízl, je připočítaný příslušný počet karet
- [x] je nastaven nový hráč na tahu

**Util**
- [x] vytvoří příslušný endpoint
- [x] ověří, že hra existuje
- [x] získá z JWT jméno hráče
- [x] zavolá metodu `game.draw_cards(<Jméno hráče, který si chce líznout>) -> <data pro odpověď>`
- [x] odpoví hráči

**Domain**
Poskytne `game.draw_cards(<Jméno hráče, který si chce líznout>) -> <data pro odpověď>`, která:
- [x] ověří, že hráč existuje a je na tahu
- [x] ověří, že hráč si smí líznout (nemá kartu, kterou by mohl zahrát)
- [x] dá hráči karty z vrcholu balíčku (příslušný počet podle toho, zda je cílem nějaké karty, nebo zda jen nemá co hrát)
- [x] notifikuje ostatní hráče, že si hráč líznul příslušný počet karet (WS Message DRAW)
- [x] vrátí příslušná data

**Comment by AurumTheEnd** [comment]
Co jsou příslušná data?

**Comment by AurumTheEnd** [comment]
Pro REST API informaci hráči vracím jako příslušná Vec\<Card>, util toho snad zdárně využije.

**Comment by holubond** [comment]
> Pro REST API informaci hráči vracím jako příslušná prozatím Vec\<Card>, util toho snad zdárně využije.

Vektor karet je v pohodě, pokud může util získat ze hry hráče na tahu.

**Comment by holubond** [comment]
Domain práce hotová, odstraňuju label
