### ISSUE TITLE
Play Card

### ISSUE THREAD

**Issue by holubond** [mazanec202/rust-uno#31]
[WIKI REST](https://github.com/mazanec202/rust-uno/wiki/HTTP-API#play-card)
[WIKI WS](https://github.com/mazanec202/rust-uno/wiki/WS-API#play-card)

Pro M1 navrhuju zasílat dotaz na server i v případě, že má danou kartu není možné zahrát. V takovém případě přijde ze serveru chybová odpověď a hráč bude nucen provést jinou akci.

**Frontend**

*Hraní karty hráčem (REST)*
 - [x] Hráč na tahu může zahrát kartu, má možnost u hraní karty říct UNO (společně jsou tyto informace zaslány na server)
 - [x] Vhodně interpretuje odpověď serveru
 - [x] jde kliknout i na karty za ukazatelem směru hry

*Reakce na akci jiného hráče (reakce na WS PLAY CARD Message)*

 - [x] hráči, který hrál kartu, je odebrána příslušná karta a je přesunuta na vrchol balíčku
 - [x] je nastaven nový hráč na tahu

**Util**
 - [x] vytvoří příslušný endpoint
 - [x] ověří, že hra existuje
 - [x] získá z JWT jméno hráče
 - [x] zavolá metodu `game.play_card(<Jméno hráče, který chce hrát>, <karta, která má být zahrána>, <optional nová barva>) -> <data pro odpověď>`
 - [x] odpoví hráči

**Domain**
Poskytne  `game.play_card(<Jméno hráče, který chce hrát>, <karta, která má být zahrána>, <optional nová barva>) -> <data pro odpověď>`, která:
 - [x] ověří, že hráč existuje a je na tahu
 - [x] ověří, že hráč smí danou kartu hrát
 - [x] odebere hráči kartu, dá ji na vrchol odhazovacího balíčku
 - [x] aktualizuje stav hry podle toho, o jakou ško kartu
 - [x] notifikuje všechny hráče o provedené akci
 - [x] pokud se hráč zbavil poslední karty, notifikuje všechny hráče pomocí WS FINISH Message
 - [x] vrátí příslušná data

**Comment by AurumTheEnd** [comment]
Co jsou příslušná data?

**Comment by AurumTheEnd** [comment]
Dle WIKI je to nic, takže vracím `anyhow::Result<()>`.

EDIT: po zavedení Err enumů vracím `Result<(), PlayCardError>`.

**Comment by holubond** [comment]
Domain práce hotová, odstraňuju label
